### ISSUE TITLE
Error in check_class(class) : assertthat::is.string(class) is not TRUE

### ISSUE THREAD

**Issue by Sidhartha10koneru** [bmihaljevic/bnclassify#60]
Hi,

I am new to bnclassify package and I am trying to use it for BBC newsclassification and I am not able to understand how i can pass the data into nb function. Whenever I try pass the dataset and class as particular category I am getting below error. Is it possible to help me to understand what can be passed to class parameter in nb function. Please delete if this is not the relevant forum to ask this question. Thanks.

**Comment by Sidhartha10koneru** [comment]
![image](https://user-images.githubusercontent.com/73468144/125332914-85141f80-e341-11eb-91be-17039265ef69.png)

**Comment by bmihaljevic** [comment]
Have you been able to solve this problem?

**Comment by Sidhartha10koneru** [comment]
Hello,
 
Yes, it was normal issue due to data not converted properly into factors, after having close look and proper conversion to factor it worked normal. Thank you for checking back on the thread.
